from easypl.learners.base import BaseLearner
from easypl.learners.classification import ClassificatorLearner
from easypl.learners.segmentation import SegmentationLearner
from easypl.learners.classification_recognition import RecognitionClassificatorLearner
